export const environment = {
  production: true,
  hostFull: 'https://api.campus.cymetria.com/',
  host: 'https://api.campus.cymetria.com/api',
  version: 'v1',
  endpoints: {
    areas: '/areas',
    users: 'users',
    user: {
      login: '/auth/login/',
      resetPassword: '/auth/password/reset/',
      confirmPassword: '/auth/password/reset/confirm/',
    },
    level: '/level',
    courses: '/courses',
    reviews: '/reviews',
    categories: '/categories',
    collaborative: '/collaborative',
    myCollaboratives: '/users/collaboratives',
    marketplace: '/marketplace',
    top: '/users/top',
    assistance: '/collaborative/assistance',
    declineAssistance: '/collaborative/decline',
    transaction: '/transaction',
    forum: {
      post: '/post',
      comment: '/comment',
    },
    order: '/order',
    connection: '/connection',
    connectionAssistance: '/connection/assistance',
    connectionDecline: '/connection/decline',
    myConnections: '/users/connections',
    testimony: '/testimony',
  },
};
