export const mockData = {
  position: '2',
  company_status: '1',
  name: 'Codificatuidea',
  department_company: '1',
  address_company: 'Calle 123',
  neighborhood_company: 'Roma',
  location_company: 'Rafael Uribe',
  phone_company: '3500903',
  mobile_company: '3114464324',
  email_company: 'ceo@codificatuidea.com',
  ccb: true,
  nit: '1030',
  start_date: null,
  org_type: '2',
  place: 'Casa',
  sales_way: '1',
  partners_number: 2,
  employes_number: 3,
  family_company: true,
  family_associated: 2,
  ciuu: '123456',
  description: 'Lorem ipsum',
  experience: '2',
  highlight: '3',
  sales: '1',
  export: '2',
  economic_sector: '2',
  problem: 'The problem',
  proposal: 'The proposal'
};

export const initialData = {
  position: null,
  company_status: null,
  name: null,
  department_company: null,
  location_company: null,
  neighborhood_company: null,
  address_company: null,
  phone_company: null,
  mobile_company: null,
  email_company: null,
  ccb: null,
  nit: null,
  start_date: null,
  org_type: null,
  place: null,
  sales_way: null,
  partners_number: null,
  employes_number: null,
  family_company: null,
  family_associated: null,
  ciuu: null,
  description: null,
  experience: null,
  highlight: null,
  sales: null,
  export: null,
  economic_sector: null,
  problem: null,
  proposal: null
};
