export const mockData = {
  document_type: 'CC',
  document: 1030557400,
  first_name: 'Sebas',
  last_name: 'Rincon',
  genre: 'M',
  birthday: null,
  department: '1',
  location: '2',
  neighborhood: 'Castilla',
  address: 'Calle 8A',
  stratum: '3',
  phone: 4500903,
  mobile: 3194562251,
  email: 'elrincon@gmail.com',
  education: '2',
  disability: '2',
  ethnic: '3',
  sexual_orientation: '2',
  activity: '4',
};

export const initialData = {
  document_type: null,
  document: null,
  first_name: null,
  last_name: null,
  genre: null,
  birthday: new Date(),
  department: null,
  location: null,
  neighborhood: null,
  address: null,
  stratum: null,
  phone: null,
  mobile: null,
  email: null,
  education: null,
  disability: null,
  ethnic: null,
  sexual_orientation: null,
  activity: null,
}
